maths/templates/maths/urls.py
from django.conf.urls import url

from . import views

app_name = 'maths'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'algo/$'),
]

maths/urls.py
from django.conf.urls import url

from . import views


app_name = 'maths'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^algo/yue/$', views.yue, name='yue'),
    url(r'^algo/stack/$', views.stack, name='stack'),
]

oxygen/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import logout
from django.contrib.auth.views import login
from django.views.generic.base import TemplateView

from . import views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url('^admin/', admin.site.urls),
    url('accounts/', include('django.contrib.auth.urls')),
    url(r'^maths/', include('maths.urls')),
    # url(r'^polls/', include('polls.urls')),
    # url(r'^weixin/', include('weixin.urls')),
]

polls/urls.py
from django.conf.urls import url

from . import views


app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
]

weixin/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'verify', views.verify, name='verify')
]

maths/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models
import django.utils.timezone
import datetime


class Question(models.Model):
    question_text = models.CharField(max_length=120)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def is_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1) 


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

maths/forms.py
from django import forms

class YueForm(forms.Form):
    x = forms.IntegerField()
    y = forms.IntegerField()

oxygen/forms.py
from django import forms
from django.forms.widgets import PasswordInput, TextInput
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(
        label='Username or email address',
        label_suffix='',
        widget=TextInput(attrs={'size': '29'})
    )
    password = forms.CharField(
        label='Password', 
        label_suffix='', 
        widget=PasswordInput(attrs={'size': '29'})
    )


class SignupForm(forms.ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=30,
        required=True,
        help_text='Usernames may contain <strong>alphanumeric</strong>, <strong>_</strong> and <strong>.</strong> characters',
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label='Confirm your password',
        required=True,
    )
    email = forms.CharField(
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
        required=True,
        max_length=75,
    )

    class Meta:
        model = User
        exclude = ['last_login', 'date_joined']
        fields = ['username', 'password', 'email', 'confirm_password']

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)

maths/views.py
from django.shortcuts import render
from django.core.cache import cache
import logging
from django.http import HttpResponse

from .forms import YueForm

logger = logging.getLogger(__name__)


def index(request):
    return render(request, 'maths/index.html')

def detail(request):
    pass

def yue(request):
    if request.method == 'POST':
        form = YueForm(request.POST)
        if form.is_valid():
            logger.info(form.cleaned_data)
            x = form.cleaned_data['x']
            y = form.cleaned_data['y']
            logger.info('%d mod %d' % (x, y))

            m = x % y
            while m:
                x = y
                y = m
                m = x % y
            
            logger.info('result: %d' % y) 
    else:
        form = YueForm()
        y = None
    
    return render(request,'maths/yue.html', {'form': form, 'y': y, 'l': [12, 2.9, 890]})

def stack(request):
    return HttpResponse('hello')

oxygen/views.py
import logging

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib import messages

from .forms import LoginForm, SignupForm

logger = logging.getLogger(__name__)

def index(request):
    logger.info('Enter index view') 
    return render(request, 'oxygen/index.html')

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse

from .models import Question, Choice

def index(request):
    all_questions = Question.objects.all()
    context = {'all_questions': all_questions}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404('不存在该问题')
    return render(request, 'polls/detail.html', {'question': question})
    
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': '没有这个选项'
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

weixin/views.py
import hashlib

from django.http import HttpResponse

from log import logger


def verify(request):
    """
    验证请求是否从微信服务器发出
    :param request:
    :return:
    """
    token = 'jcloud'
    timestamp, nonce = request.GET.get('timestamp'), request.GET.get('nonce')
    a_list = [token, timestamp, nonce]
    logger.info(a_list)
    if timestamp is None:
        logger.info('Can not get parameter timestamp')
        return HttpResponse('Timestamp is None', content_type='text/plain')

    a_list.sort()
    sorted_str = ''.join(i for i in a_list)
    local_signature = hashlib.sha1(sorted_str.encode()).hexdigest()
    logger.info('计算出来的 signature: %s', local_signature)
    remote_signature = request.GET.get('signature')
    logger.info('传过来的 signature: %s', remote_signature)
    if remote_signature == local_signature:
        echostr = request.GET.get('echostr')
        logger.info(echostr)
        return HttpResponse(echostr, content_type='text/plain')

maths/templates/maths/index.html
{% load static %}

<h1>历年中考数学题</h1>
<ul>
	<li>
		<a href="">2017年北京市高级中等学校招生考试</a>
	</li>
</ul>

maths/templates/maths/stack.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'maths/style.css' %}" />
<p>
	{% if y %}
		result: {{ y }}
	{% else %}
		result: 
	{% endif %}
</p>

<ul class="list-group">
	{% for i in l %}
		<li class="list-group-item">{{ i }}</li>
	{% endfor %}
</ul>

maths/templates/maths/yue.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'maths/style.css' %}" />

<form action="{% url 'maths:yue' %}" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit" class="btn btn-outline-primary btn-lg">calculate</button>
</form>

<div class="card">
	<div class="card-body">
		<h5 class="card-title">result</h5>
		<p class="card-text">
			{% if y %}
				{{ y }}
			{% endif %}
		</p>
	</div>
</div>

oxygen/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
	<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
	<script src="{% static 'js/popper.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<title>{% block title %}EdPro{% endblock%}</title>
</head>

<body>
	<div id="header">
	{% block header %}
		<nav class="navbar navbar-inverse navbar-static-top bg-dark" role="navigation">
			<div class="navbar-header">
				<a class="navbar-brand text-light"
					href="{% url 'index' %}">
					EdPro
				</a>
			</div>
			<a class="nav-item nav-link text-light" href="{% url 'maths:index' %}">Maths</a>
			<a class="nav-item nav-link text-light" href="#">Python</a>
			<a class="nav-item nav-link text-light" href="#">Java</a>

		<ul class="nav navbar-nav navbar-right">
			{% if user.is_authenticated %}
				<div class="nav-item nav-link text-light">
					{% trans "Logged in" %}: {{ user.username }}
				</div>
				<a class="nav-item nav-link text-light 
					"href="{% url 'logout' %}">{% trans "Log out" %}</a> |
			{% else %} 
				<a class="nav-item nav-link text-light "href="{% url 'login' %}">
					{% trans "Log in" %}
			</a> {% endif %}
		</ul>
		</nav>
	{% endblock %}
	</div>
	
	<div id="content">
	{% block content %}{% endblock %}
	</div>

	<div id="footer">
	{% block footer %}
		<hr />
	{% endblock %}
	</div>
</body>

</html>

oxygen/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
	ProEd
{% endblock %}

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}
	<p>
		<strong>{{ error_message }}</strong>
	</p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
	<lable for="choice{{ forloop.counter }}">{{ choice.choice_text }}</lable><br /><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1>待投票的问题</h1>
{% if all_questions %}
	<ul>
		{% for question in all_questions %}
			<li><a href="{% url 'polls:detail' question.id %}">
				{{ question.id }}: {{ question.question_text }}
			</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>没有问题要显示！</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
	{% for choice in question.choice_set.all %}
		<li>
			{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
		</li>
	{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>